# Generated by Django 3.2.23 on 2026-03-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malar_app', '0003_auto_20260306_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kilogram'), ('g', 'Gram'), ('litre', 'Litre'), ('ml', 'Millilitre'), ('meter', 'Meter'), ('cm', 'Centimeter'), ('box', 'Box'), ('pack', 'Pack'), ('dozen', 'Dozen'), ('roll', 'Roll'), ('bottle', 'Bottle'), ('can', 'Can'), ('set', 'Set'), ('pair', 'Pair'), ('other', 'Other')], default='piece', help_text='Measurement unit for this product', max_length=50),
        ),
    ]
