# Generated by Django 3.2.23 on 2026-03-21 06:39

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malar_app', '0004_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='India', max_length=100)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission % for this dealer', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='dealer',
            field=models.ForeignKey(blank=True, help_text='Dealer who distributed this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='malar_app.dealer'),
        ),
        migrations.AddField(
            model_name='product',
            name='dealers',
            field=models.ManyToManyField(blank=True, help_text='Select dealers who distribute this product', related_name='products', to='malar_app.Dealer'),
        ),
    ]
